config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'rooms#index'
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :room_messages
  resources :rooms, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, inverse_of: :room, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  include UsersHelper
  include RoomMessagesHelper

  belongs_to :room, inverse_of: :room_messages
  belongs_to :user

  validates :message, presence: true

  def as_json options
    super(options).merge \
      user_avatar_url: gravatar_for(current_user, size: 32),
      time_format:     message_time_format(self)
  end

  private

  def current_user
    user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :room_messages, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include BrowserCache

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [:username]
  end
end

app/controllers/concerns/browser_cache.rb
# Clean browser cache
# When user logs out and clicks back button on the browser
# this prevents to see the previous page.
module BrowserCache
  extend ActiveSupport::Concern

  included do
    before_action :set_cache_headers
  end

  private

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"]        = "no-cache"
    response.headers["Expires"]       = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_room

  def create
    @room_message = RoomMessage.new \
      user:    current_user,
      room:    @room,
      message: params.dig(:room_message, :message)

    if @room_message.save
      head :ok

      RoomChannel.broadcast_to @room, @room_message
    else
      render json: { errors: @room_message.errors }, status: :unprocessable_entity
    end
  end

  private

  def load_room
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_rooms, except: %i[new create]

  def index; end

  def show
    @room_message  = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes :user
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new room_params

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @room.update room_params
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def load_rooms
    @room  = Room.find params[:id] if params[:id]
    @rooms = Room.all
  end

  def room_params
    params.require(:room).permit :name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
  def message_time_format message
    # "%T" == "%H:%M:%S"
    if message.created_at.today?
      message.created_at.strftime "%T"
    else
      message.created_at.strftime "%b-%d-%Y"
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: 200
    gravatar_id = Digest::MD5.hexdigest user.email.downcase

    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

    gravatar_url
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    = csrf_meta_tags
    = csp_meta_tag

    = action_cable_meta_tag if user_signed_in?

    link[
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css"]

    = stylesheet_link_tag    'application', media: :screen, 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    title ChatApp

  body
    = render 'shared/header'

    .row style="max-width: 100%;"
      .col-md-10.offset-1
        = render 'shared/notifications'

        = yield

app/views/room_messages/_message_template.slim
.d-none data-role="message-template"
  .chat-message-container
    .row.no-gutters
      .col-auto.text-center
        = image_tag "", class: "avatar", alt: "user image", data: { role: "user-avatar" }

      .col
        .message-content
          .mb-1 data-role="message-text"

          .text-right
            small data-role="message-date"

app/views/room_messages/_room_message.slim
.chat-message-container
  .row.no-gutters
    .col-auto.text-center
      = image_tag gravatar_for(current_user, size: 32), class: "avatar", alt: "user img"

    .col
      .message-content
        .mb-1 = room_message.message

        .text-right
          small = message_time_format room_message

app/views/room_messages/_room_message_form.slim
= form_for room_message, remote: true do |f|
  = hidden_field :room_message, :room_id

  .input-group
    = f.text_area :message,
      placeholder: "Enter your message",
      autofocus:   true,
      class:       "form-control chat-input"

    .input-group-append
      = f.button :submit, class: 'btn btn-primary chat-input room-message-btn' do
        i.fas.fa-paper-plane style="transform: rotate(30deg);"

app/views/rooms/_room_form.slim
= form_for room do |f|
  = render 'shared/error_notifications', object: f.object

  .form-group
    = f.text_field :name,
      autocomplete: "on",
      placeholder:  "Enter room name",
      autofocus:    true,
      class:        "form-control"

  .form-group
    = f.submit buttonText, class: "btn btn-sm btn-primary"

app/views/rooms/_rooms.slim
.mb-3
  = link_to 'Create a room', new_room_path, class: "btn btn-primary"

- if rooms.present?
  nav.nav.flex-column
    - rooms.each do |room|
      = link_to room.name, room, class: "nav-link room-nav-link"
- else
  .text-muted The are no rooms

app/views/rooms/edit.slim
h1 Change room name

= render 'room_form', room: @room, buttonText: 'Change'

app/views/rooms/index.slim
.row
  .col-12.col-md-3
    = render 'rooms', rooms: @rooms

  .col
    .alert.alert-primary
      h4.alert-heading Welcome to the RailsChatTutorial!

      p We need to talk.
      hr
      p You can create or join a room from the sidebar.

app/views/rooms/new.slim
h1 Create room

= render 'room_form', room: @room, buttonText: 'Create'

app/views/rooms/show.slim
h1 = @room.name

.row
  .col-12.col-md-3
    = render 'rooms', rooms: @rooms

  .col
    .chat data-channel-subscribe="room" data-room-id="#{@room.id}"
      = render @room_messages

    .message-form
      = render 'room_messages/room_message_form', room_message: @room_message

= render 'room_messages/message_template'

app/views/shared/_error_notifications.slim
- if object.errors.any?
  .alert.alert-danger style="background-color: transparent;border: none;color: #d9534f" role="alert"
    = tag.button type: :button,
      class: :close,
      data: { dismiss: "alert" },
      aria: { label: "Close" } do
      = tag.span "&times;".html_safe, aria: { hidden: true }, style: "color: #d9534f"

    ' The form contains #{pluralize object.errors.count, "error"}

    ul
      - object.errors.full_messages.each do |msg|
        li style="list-style: none;" = msg

app/views/shared/_header.slim
nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top"
  a class="navbar-brand" href="#{root_path}" Chat App

  button[
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation"]
    span class="navbar-toggler-icon"

  - if user_signed_in?
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        li.nav-item.dropdown
          a[
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"]
            => image_tag (gravatar_for current_user, size: 50), class: "user-image"
            span #{current_user.username}

          .dropdown-menu.dropdown-menu-right aria-labelledby="dropdownMenuOffset"

            a.dropdown-item href="#{edit_user_registration_path}"
              i.fa.fa-user.mr-1
              | Profile

            .dropdown-divider

            a.dropdown-item rel="nofollow" href="#{destroy_user_session_path}" data-method="delete"
              i.fas.fa-sign-out-alt.mr-1
              | Log out
  - else
    ul.navbar-nav.ml-auto.sign-in-sign-out
      li.nav-item
        = link_to new_user_registration_path, class: "nav-link" do
          i.fas.fa-user-plus.mr-1
          | Sign up

      li.nav-item
        = link_to user_session_path, class: "nav-link" do
          i.fas.fa-sign-in-alt.mr-1
          | Sign in

app/views/shared/_notifications.slim
- unless flash[:alert]
  #notifications
    - flash.each do |msg_type, msg|
      = tag.div id: msg_type, class: "alert alert-#{msg_type}", role: "alert" do
        - if msg_type.eql?("danger") || msg_type.eql?("warning")
          = tag.button type: :button,
            id: "button",
            class: :close,
            data: { dismiss: "alert-#{msg_type}" },
            aria: { label: "Close" } do
            = tag.span "&times;".html_safe, aria: { hidden: true }

        = sanitize msg